# MySQL.  Versions 4.1 and 5.0 are recommended.
#
#
# Be sure to use new-style password hashing:
#   http://dev.mysql.com/doc/refman/5.0/en/old-client.html
development:
  adapter: mysql
  #database: openmrs_development
  database: dm_quech
  username: root
  password: password
  host: localhost

test:
  adapter: mysql
  #database: openmrs_test
  database: dm_zch
  username: root
  password: password
  host: localhost

production:
  adapter: mysql
  #database: openmrs_production
  database: dm_zch
  username: root
  password: password
  host: localhost

